name: Uptime Monitor Update

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  update-uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run uptime monitor
        run: node monitor.js

      - name: Checkout gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages || git checkout -b gh-pages

      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add uptime.json
          git commit -m "Updated uptime data"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
